<a href="https://colab.research.google.com/github/Manasa-kodeboyena/Machine-learning-repo/blob/main/ML_Lab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question -1

In [ ]:
import numpy as np
a = np.arange(1,21)
print(a)
print(a.shape)
print(np.max(a))
print(np.min (a))
print(np.mean(a))
print(np.std(a))
new_matrix=a.reshape(4, 5)
print(new_matrix)
print(new_matrix[1])
print(new_matrix[:,2])

Question-2

In [ ]:
import numpy as np
A = np.array([10,20,30,40, 50])
B = np.array([5,10,15,20,25])
add = A+B
print(add)
sub = A-B
print(sub)
mul = A*B
print(mul)
allSum = np.sum(A)
print(allSum)

Question-3

In [ ]:
import pandas as pd
data = {
    'rollno' : [101,102,103,104,105],
    'Name' : ['Ravi','Priya','kiran','Anu','sita'],
    'Marks' : [85,92,78,88,95]
}
df = pd.DataFrame(data)
display(df)
print(df.head(3))
avg_marks = df['Marks'].mean()
print(avg_marks)
highest_marks_name = df.loc[df['Marks'].idxmax(), 'Name']
lowest_marks_name = df.loc[df['Marks'].idxmin(), 'Name']
print(highest_marks_name)
print(lowest_marks_name)
conditions = [
    (df['Marks'] > 90),
    ((df['Marks'] >=80) & (df['Marks']<=89)),
    (df['marks'] < 80)
]
choices ['A','B', 'C']
df['Grade'] = np.select(conditions, choices)
print(df)

Question-4

In [ ]:
import pandas as pd
data = {
    'Product':['Laptop','Mouse','Keyboard','Monitor'],
    'Price' : [50000,500,1200,10000],
    'Quantity':[10,50,30,15]
}
df = pd.DataFrame(data)
display(df)
#Calculate and add the total value of each product
df['Total Value'] = df['Price'] *df['Quantity']
display(df)
#highest total value product
highest_total_value_product = df.loc[df['Total Value'].idxmax(), 'Product']
print(highest_total_value_product)
#calculate the overall inventory value
total_value = df['Total Value'].sum()
print(total_value)

    Product  Price  Quantity
0    Laptop  50000        10
1     Mouse    500        50
2  Keyboard   1200        30
3   Monitor  10000        15

    Product  Price  Quantity  Total Value
0    Laptop  50000        10       500000
1     Mouse    500        50        25000
2  Keyboard   1200        30        36000
3   Monitor  10000        15       150000

Laptop
711000

In [ ]:
import pandas as pd
df = pd.read_csv('iris.csv')
# first 5
display(df.head(5))
#no. of rows and columns
dimensions = df.shape
print(dimensions)
#display cloumn names
print(df.columns)
#missing counts
missing_counts = df.isnull().sum()
print(missing_counts)
#summary statistics for numerical summary
numerical_summary = df.describe()
display(numerical_summary)
#the number of samples belonging to each class.
class_counts = df['virginica'].value_counts()
print("--- Class Distribution ---")
print(class_counts)

   150    4  setosa  versicolor  virginica
0  5.1  3.5     1.4         0.2          0
1  4.9  3.0     1.4         0.2          0
2  4.7  3.2     1.3         0.2          0
3  4.6  3.1     1.5         0.2          0
4  5.0  3.6     1.4         0.2          0

(150, 5)
Index(['150', '4', 'setosa', 'versicolor', 'virginica'], dtype='object')
150           0
4             0
setosa        0
versicolor    0
virginica     0
dtype: int64

              150           4      setosa  versicolor   virginica
count  150.000000  150.000000  150.000000  150.000000  150.000000
mean     5.843333    3.057333    3.758000    1.199333    1.000000
std      0.828066    0.435866    1.765298    0.762238    0.819232
min      4.300000    2.000000    1.000000    0.100000    0.000000
25%      5.100000    2.800000    1.600000    0.300000    0.000000
50%      5.800000    3.000000    4.350000    1.300000    1.000000
75%      6.400000    3.300000    5.100000    1.800000    2.000000
max      7.900000    4.400000    6.900000    2.500000    2.000000

--- Class Distribution ---
virginica
0    50
1    50
2    50
Name: count, dtype: int64